CURRENCY_EURO = 'EUR'
CURRENCY_GBP = 'GBP'
CURRENCY_BITCOIN = 'BTY'
CURRENCY_CHOICES = (
    (CURRENCY_EURO, CURRENCY_EURO),
    (CURRENCY_GBP, CURRENCY_GBP),
    (CURRENCY_BITCOIN, CURRENCY_BITCOIN)
)
