# Generated by Django 3.0.6 on 2020-08-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='payment_type',
            field=models.CharField(choices=[('Prepaid Card', 'Prepaid Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], default='Prepaid Card', max_length=16, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='is_used',
            field=models.NullBooleanField(default=False, verbose_name='Is Used'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='serial_num',
            field=models.BigIntegerField(unique=True, verbose_name='Serial Number'),
        ),
    ]
