# Generated by Django 3.0.6 on 2020-06-21 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('home', models.CharField(max_length=64, verbose_name='Home')),
                ('away', models.CharField(max_length=64, verbose_name='Away')),
                ('home_odds', models.FloatField(verbose_name='Home Odds')),
                ('away_odds', models.FloatField(verbose_name='Away Odds')),
                ('draw_odds', models.FloatField(verbose_name='Draw Odds')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('result', models.CharField(blank=True, choices=[('Home Win', 'Home Win'), ('Away Win', 'Away Win'), ('Draw', 'Draw'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=32, null=True, verbose_name='Result')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial Number')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Code')),
                ('value', models.CharField(blank=True, max_length=128, null=True, verbose_name='Value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(max_length=64, verbose_name='Selection')),
                ('side', models.CharField(max_length=4, verbose_name='Side')),
                ('odds', models.FloatField(verbose_name='Odds')),
                ('stake', models.FloatField(verbose_name='Stake')),
                ('matched', models.BooleanField(default=False, verbose_name='Matched')),
                ('has_won', models.NullBooleanField(verbose_name='Has Won')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Event', verbose_name='Event')),
                ('matched_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bets.Bet', verbose_name='Matched With')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
