# Generated by Django 3.0.6 on 2020-08-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20200726_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='away_odds',
        ),
        migrations.RemoveField(
            model_name='event',
            name='draw_odds',
        ),
        migrations.RemoveField(
            model_name='event',
            name='home_odds',
        ),
        migrations.RemoveField(
            model_name='event',
            name='result',
        ),
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(default='', max_length=64, verbose_name='External API ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='league',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='market_results',
            field=models.TextField(default='', verbose_name='Market Results'),
        ),
        migrations.AddField(
            model_name='event',
            name='match_result',
            field=models.CharField(blank=True, choices=[('Home Win', 'Home Win'), ('Away Win', 'Away Win'), ('Draw', 'Draw'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=32, null=True, verbose_name='Match Result'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sport_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
