# Generated by Django 3.0.6 on 2020-08-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_auto_20200818_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='match_result',
            field=models.CharField(blank=True, choices=[('Home Win', 'Home Win'), ('Away Win', 'Away Win'), ('Draw', 'Draw'), ('Upcoming', 'Upcoming'), ('Live', 'Live')], default='Upcoming', max_length=32, null=True, verbose_name='Match Result'),
        ),
    ]
