# Generated by Django 3.0.6 on 2020-08-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_auto_20200825_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scores',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Scores'),
        ),
        migrations.AlterField(
            model_name='event',
            name='match_result',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Home Win', 'Home Win'), ('Away Win', 'Away Win'), ('Draw', 'Draw'), ('Cancelled', 'Cancelled'), ('Live', 'Live'), ('Concluded', 'Concluded'), ('Unknown', 'Unknown')], default='Upcoming', max_length=32, null=True, verbose_name='Match Result'),
        ),
    ]
