# Generated by Django 3.0.6 on 2020-09-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_auto_20200831_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scoreboard',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Scoreboard'),
        ),
        migrations.AlterField(
            model_name='event',
            name='market_results',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Market Results'),
        ),
        migrations.AlterField(
            model_name='event',
            name='match_result',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Concluded', 'Concluded'), ('Home Win', 'Home Win'), ('Away Win', 'Away Win'), ('Draw', 'Draw'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=32, null=True, verbose_name='Match Result'),
        ),
    ]
