# Generated by Django 3.0.6 on 2020-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Balance'),
        ),
    ]
