# Generated by Django 3.0.6 on 2020-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Country'),
        ),
    ]
