# Generated by Django 3.0.6 on 2020-07-26 17:19

import Betty.apps.authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200712_0533'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Betty.apps.authentication.managers.CustomUserManager()),
            ],
        ),
    ]
